version: '3.8'
services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./django_project/postgres.env
      - ./flask_project/postgres.env

  migrate_service:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python manage.py migrate --noinput
    volumes:
      - ./django_project:/app
    env_file:
      - ./django_project/postgres.env
    depends_on:
      - postgres_db

  create_superuser:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python create_superuser.py
    volumes:
      - ./django_project:/app
    env_file:
      - ./django_project/postgres.env
    depends_on:
      - migrate_service

  backend:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./django_project:/app
    env_file:
      - ./django_project/postgres.env
    depends_on:
      - create_superuser
      - postgres_db

  django_consumer:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python consumer.py
    volumes:
      - ./django_project:/app
    env_file:
      - ./django_project/postgres.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings # Set DJANGO_SETTINGS_MODULE here
    depends_on:
      - postgres_db
      - migrate_service
      - create_superuser


  flask_migrate:
    build:
      context: ./flask_project
      dockerfile: Dockerfile
    command: flask db upgrade
    volumes:
      - ./flask_project:/app
    env_file:
      - ./flask_project/postgres.env
    depends_on:
      - postgres_db

  flask_app:
    build:
      context: ./flask_project
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./flask_project:/app
    env_file:
      - ./flask_project/postgres.env
    depends_on:
      - flask_migrate
      - postgres_db

  flask_consumer:
    build:
      context: ./flask_project
      dockerfile: Dockerfile # Path to Flask Dockerfile
    command: python consumer.py 
    volumes:
      - ./flask_project:/app
    env_file:
      - ./flask_project/postgres.env # Flask project environment file
    depends_on:
      - postgres_db
      

volumes:
  postgres_data:
